### ISSUE TITLE
Error: runtimeerror: mat1 and mat2 shapes cannot be multiplied (1x1 and 768x32)

### ISSUE THREAD

**Issue by Jana-alt** [HumaticsLAB/POP-Mining-POtential-Performance#3]
I have the error with training after it download data and makes in wandb :

runtimeerror: mat1 and mat2 shapes cannot be multiplied (1x1 and 768x32)

**Comment by Jana-alt** [comment]
![‏‏لقطة الشاشة (749)](https://user-images.githubusercontent.com/74506807/220785376-c7f0fa1c-ca54-4254-8907-30e709be3cd1.png)

**Comment by Jana-alt** [comment]
![‏‏لقطة الشاشة (745)](https://user-images.githubusercontent.com/74506807/220785484-5d5364fd-bbb2-4fe2-b393-a9433bdcc417.png)

**Comment by joppichristian** [comment]
Hi,
this error arises with the wrong version of transformers package. 

https://github.com/HumaticsLAB/POP-Mining-POtential-Performance/blob/b0682f1271f17f14bfc5b313b9dd7c601affb9e0/models/GTM.py#L7

Which version did you install? Please, try to install version 4.11.3.

**Comment by Jana-alt** [comment]
![image](https://user-images.githubusercontent.com/74506807/221061489-027945f6-988a-4f2d-97e0-b971326f855a.png)
I try and still the same error

**Comment by Jana-alt** [comment]
![image](https://user-images.githubusercontent.com/74506807/221061681-12bb2e6a-9e73-42ff-9b6b-1719f145e606.png)

**Comment by Jana-alt** [comment]
Hello how are you?
I hope you are well

Me and my team we have a graduation project and we want to work on the code
  POP-Mining-POtential-Performance. We will make cite for you.

thanks for your answer and I tried it but the error remains the same can
you please help us this our wok on colab can you check it
if there is something I need to change

I download dataset form google drive and I change the paths in
trainer_pop_py

https://colab.research.google.com/drive/1GCpZIYBew3aWHHWOfQfs_sUViwmIZkUz?usp=sharing

or this one
https://colab.research.google.com/drive/1GEmQJPdLlriqYbNdvP7bR1tVD0OUjDBH?usp=sharing

**Comment by joppichristian** [comment]
try to install version 4.9.1

**Comment by Jana-alt** [comment]
Thank you it is working now
